language: go
go:
  - 1.23.2
  - 1.22.2
  - 1.21.9
os:
  - linux
install:
  - go get -v github.com/zquestz/geoclue-tz
script:
  - go build
  - go fmt ./...
  - go vet ./...
  - go test -i -race ./...
  - go test -v -race ./...
after_script:
  - if [ "$TRAVIS_GO_VERSION" = "1.23.2" ] && [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_TAG" != "" ]; then go get github.com/inconshreveable/mousetrap; fi
  - if [ "$TRAVIS_GO_VERSION" = "1.23.2" ] && [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_TAG" != "" ]; then go install github.com/mitchellh/gox; fi
  - if [ "$TRAVIS_GO_VERSION" = "1.23.2" ] && [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_TAG" != "" ]; then go install github.com/tcnksm/ghr; fi
  - if [ "$TRAVIS_GO_VERSION" = "1.23.2" ] && [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_TAG" != "" ]; then make compile; ghr --username zquestz --token $GITHUB_TOKEN --replace $TRAVIS_TAG pkg/; fi
